#ifndef TOKENS_H
#define TOKENS_H

enum TokenType {
    T_IF = 256, T_ELSE, T_TRUE, T_FALSE, T_FN, T_RETURN, T_CLASS, T_FROM,
    T_FOR, T_WHILE, T_SWITCH, T_DO, T_CONTINUE, T_CASE, T_TRY, T_CATCH,
    T_FINALLY, T_IMPORT, T_BREAK,

    T_STRING, T_INT, T_FLOAT, T_CHAR, T_BOOL,

    T_IDENTIFIER, T_STRING_LITERAL, T_INT_LITERAL, T_FLOAT_LITERAL, T_CHAR_LITERAL, T_BOOL_LITERAL,

    T_PLUS, T_MINUS, T_MUL, T_DIV,
    T_ASSIGN, T_ARROW, T_EQ, T_NEQ, T_LT, T_GT, T_LTE, T_GTE,
    T_TYPEANNOTATION, // ::

    T_LPAREN, T_RPAREN, T_LBRACE, T_RBRACE, T_LBRACK, T_RBRACK,
    T_COMMA, T_COLON, T_SEMICOLON
};

#endif